Commutatus Assignment/force-app/main/default/objects/Account/fields/Profile_Completed__c.field-meta.xml
<CustomField>
    <fullName>Profile_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Once the User fills the details then we can set the field to checked</description>
    <label>Profile Completed</label>
    <type>Checkbox</type>
</CustomField>

Commutatus Assignment/force-app/main/default/objects/Account/fields/Shoe_size__c.field-meta.xml
<CustomField>
    <fullName>Shoe_size__c</fullName>
    <description>The shoe sizes are between 6 and 16 (inclusive), incrementing by 0.5</description>
    <label>Shoe size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6</fullName>
                <default>true</default>
                <label>6</label>
            </value>
            <value>
                <fullName>6.5</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>7.5</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>8.5</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>9.5</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>10.5</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>11.5</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>12.5</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>13.5</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>14.5</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>15.5</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Commutatus Assignment/force-app/main/default/objects/Account/fields/T_Shirt_Size__c.field-meta.xml
<CustomField>
    <fullName>T_Shirt_Size__c</fullName>
    <description>The t-shirt sizes are: XS, S, M, L, XL, XXL</description>
    <label>T Shirt Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>XS</fullName>
                <default>true</default>
                <label>XS</label>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>XL</fullName>
            </value>
            <value>
                <fullName>XXL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Commutatus Assignment/force-app/main/default/classes/ApexCalloutTest.cls
@istest
private class ApexCalloutTest {
    
    @testsetup
    private static void accountData(){
        Account testAccount=new Account(FirstName='sample',lastName='test',Phone='1234567890',PersonEmail = 'test@example.com', T_Shirt_Size__c = 'M', Shoe_size__c = '9');
        insert testAccount;
    }
    
    @istest static Account getAccountdata(){
        Account acc=[select id,PersonEmail,T_Shirt_Size__c,Shoe_size__c,Loyalty_Customer_ID__c FROM Account];
        return   ApexCallout.getAccountRecordId(acc.Id);
        
    }
    
    @istest static void updateAccountdata(){
        Account acc=[select id,PersonEmail,T_Shirt_Size__c,Shoe_size__c,Loyalty_Customer_ID__c FROM Account];   
        ApexCallout.updateAccountWithCustomerId('123455', acc);  
    }
    
    @istest static void negativeUpdateAccountdata(){
        Account acc=[select id,PersonEmail,T_Shirt_Size__c,Shoe_size__c,Loyalty_Customer_ID__c FROM Account];   
        try{
            ApexCallout.updateAccountWithCustomerId('1223', null); 
        }catch(Exception e){
            String expectedErrorMessage = 'System.NullPointerException: Attempt to de-reference a null object';
            System.assertEquals(expectedErrorMessage, e.getMessage(), 'Exception message should match');
            System.assertEquals(false, acc.Profile_Completed__c, 'Profile_Completed__c should not be updated');
        }
        
    }
    
    @istest static void httpCallout(){
        Account acc=[select id,PersonEmail,T_Shirt_Size__c,Shoe_size__c,Loyalty_Customer_ID__c FROM Account];   
        Test.startTest();
        // Call the method being tested
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        ApexCallout.sendHttpPostRequest(acc.Id);
        Test.stopTest(); 
    }
    
    @istest static void negativeHttpCallout(){
        Account acc=[select id,PersonEmail,T_Shirt_Size__c,Shoe_size__c,Loyalty_Customer_ID__c FROM Account];   
        Test.startTest();
        // Call the method being tested
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        try{
            ApexCallout.sendHttpPostRequest(null);
            Test.stopTest(); 
        }catch(Exception e){
            String expectedErrorMessage = 'System.NullPointerException: Attempt to de-reference a null object';
            System.assertEquals(expectedErrorMessage, e.getMessage(), 'Exception message should match');
            
        }
    }
}