Commutatus Assignment/force-app/main/default/objects/Account/fields/Profile_Completed__c.field-meta.xml
<CustomField>
    <fullName>Profile_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Once the User fills the details then we can set the field to checked</description>
    <label>Profile Completed</label>
    <type>Checkbox</type>
</CustomField>

Commutatus Assignment/force-app/main/default/objects/Account/fields/Shoe_size__c.field-meta.xml
<CustomField>
    <fullName>Shoe_size__c</fullName>
    <description>The shoe sizes are between 6 and 16 (inclusive), incrementing by 0.5</description>
    <label>Shoe size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6</fullName>
                <default>true</default>
                <label>6</label>
            </value>
            <value>
                <fullName>6.5</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>7.5</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>8.5</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>9.5</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>10.5</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>11.5</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>12.5</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>13.5</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>14.5</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>15.5</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Commutatus Assignment/force-app/main/default/objects/Account/fields/T_Shirt_Size__c.field-meta.xml
<CustomField>
    <fullName>T_Shirt_Size__c</fullName>
    <description>The t-shirt sizes are: XS, S, M, L, XL, XXL</description>
    <label>T Shirt Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>XS</fullName>
                <default>true</default>
                <label>XS</label>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>XL</fullName>
            </value>
            <value>
                <fullName>XXL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Commutatus Assignment/force-app/main/default/classes/ApexCallout.cls
global class ApexCallout {
    @future(callout=true)
    public static void sendHttpPostRequest(String recordId) {
        // Define the URL endpoint
       try {
        String endpoint = 'https://integrations.commutatus.com/webhook/719ce78d-c2c5-47a8-986a-39d7e7a5652d';
        Account acc=getAccountRecordId(recordId);
        // Define the request body
        String requestBody = '{ "email":"'+ acc.PersonEmail+'", "tshirtSize":"'+acc.T_Shirt_Size__c+'", "shoeSize":"'+acc.Shoe_size__c+'" }';
        
        System.debug('requestBody'+requestBody);
        // Create a new HTTP request
        HttpRequest httpRequest = new HttpRequest();
        httpRequest.setEndpoint(endpoint);
        httpRequest.setMethod('POST');
        httpRequest.setHeader('Content-Type', 'application/json');
        httpRequest.setBody(requestBody);
        
        // Create a new HTTP object to send the request
        Http http = new Http();
        
        
            // Send the request and get the response
            HttpResponse httpResponse = http.send(httpRequest);
            
            system.debug('httpResponse '+httpResponse);
            // Check the response status
            if (httpResponse.getStatusCode() == 200) {
                // Parse the response JSON
                Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(httpResponse.getBody());
                system.debug('responseMap '+responseMap);
                String customerId = String.valueOf(responseMap.get('customer_id'));
                system.debug('customerId '+customerId);
                // Update the Account record with the customer ID
                updateAccountWithCustomerId(customerId,acc);
            } else {
                System.debug('Request failed with status code: ' + httpResponse.getStatusCode() + ' and message: ' + httpResponse.getStatus());
            }
        } catch (Exception e) {
            System.debug('Exception caught: ' + e.getMessage());
        }
    }
    @testvisible
    private static void updateAccountWithCustomerId(String customerId,Account acc) {
        try {
            
            // Update the Account records with the customer ID
            Account account =acc;
            account.Loyalty_Customer_ID__c = customerId;
            account.Profile_Completed__c=true;
            
            // Perform DML operation to update the records
            
            update account;
        } catch (Exception e ) {
            System.debug('Error updating Account records: ' + e.getMessage());
        }
    }
    
    @testvisible
    private static Account getAccountRecordId(String recordId){
        Account acc=[select id,PersonEmail,T_Shirt_Size__c,Shoe_size__c,Loyalty_Customer_ID__c FROM Account where id = : recordId];
        return acc;
    }
}