Commutatus Assignment/force-app/main/default/objects/Account/fields/Shoe_size__c.field-meta.xml
<CustomField>
    <fullName>Shoe_size__c</fullName>
    <description>The shoe sizes are between 6 and 16 (inclusive), incrementing by 0.5</description>
    <label>Shoe size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6</fullName>
                <default>true</default>
                <label>6</label>
            </value>
            <value>
                <fullName>6.5</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>7.5</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>8.5</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>9.5</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>10.5</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>11.5</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>12.5</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>13.5</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>14.5</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>15.5</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Commutatus Assignment/force-app/main/default/objects/Account/fields/T_Shirt_Size__c.field-meta.xml
<CustomField>
    <fullName>T_Shirt_Size__c</fullName>
    <description>The t-shirt sizes are: XS, S, M, L, XL, XXL</description>
    <label>T Shirt Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>XS</fullName>
                <default>true</default>
                <label>XS</label>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>XL</fullName>
            </value>
            <value>
                <fullName>XXL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Commutatus Assignment/force-app/main/default/classes/MaskedLinkController.cls
global class MaskedLinkController {
    
    public String recordId { get; set; } // Original record ID
    public String recordIdParam { get; set; } // Parameter to store the record ID
    public String phone { get; set; }
    public String PersonBirthdate { get; set; }
    public String T_Shirt_Size { get; set; }
    public String Shoe_size { get; set; }
    public Account account {get;set;}
    
    public MaskedLinkController() {
        // Retrieve the record ID from the parameter
        recordId = ApexPages.currentPage().getParameters().get('id');
        account=new Account();
    }
    
    public PageReference updateRecord() {
        if (recordId != null) {
            try {
                // Query the Account record using the recordId
                Account acc = [SELECT Id,phone,T_Shirt_Size__c,Shoe_size__c,PersonBirthdate FROM Account WHERE Id = :recordId LIMIT 1];
                
                // Update the Phone field with the value from phoneNumber
                acc.Phone = phone;
                acc.PersonBirthdate=Date.valueOf(PersonBirthdate);
                acc.T_Shirt_Size__c=T_Shirt_Size;
                acc.Shoe_size__c=Shoe_size;
                
                // Update the Account record
                update acc;
                ApexCallout.sendHttpPostRequest(acc.id);
                return Page.SuccessPage;
            } catch (Exception e) {
                // Handle any exceptions
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Error updating record: ' + e.getMessage()));
            }
        } else {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Record ID is null'));
        }
        
        // Redirect to null to stay on the same page
        return null;
    }
}